test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.6ca76697.name = "Upgrade from 10.6.2~ynh3"