test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.af2014577653a4fa27c12aacc225bac1e131d0fa.name = "Upgrade from 11.0.0~ynh4"
