#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --keep="airsonic.properties"
fi

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression "Adding multimedia directories..."

ynh_multimedia_build_main_dir
ynh_multimedia_addfolder --source_dir="/home/yunohost.app/$app/Podcasts" --dest_dir="share/Podcasts"
ynh_multimedia_addfolder --source_dir="/home/yunohost.app/$app/Playlists" --dest_dir="share/Playlists"
# Allow airsonic to write into these directories
ynh_multimedia_addaccess $app

if ! grep -q "PodcastFolder" $install_dir/airsonic.properties; then
	echo "PodcastFolder=/home/yunohost.multimedia/share/Podcasts" >> $install_dir/airsonic.properties
fi

if ! grep -q "PlaylistFolder" $install_dir/airsonic.properties; then
	echo "PlaylistFolder=/home/yunohost.multimedia/share/Playlists" >> $install_dir/airsonic.properties
fi

# Allow Airsonic to write into these directories
ynh_multimedia_addaccess $app

#=================================================
# ENABLE "TRANSCODE"
#=================================================
ynh_script_progression "Enabling transcode..."

### For details, see https://airsonic.github.io/docs/transcode/

mkdir -p $install_dir/transcode

if [ -x /usr/bin/ffmpeg -a ! -e $install_dir/transcode/ffmpeg ]; then   # Check if 'ffmpeg' is installed, executable and that the symlink doesn't exist
	ln -s /usr/bin/ffmpeg $install_dir/transcode
fi

# FIXME Not sure if 'lame' is needed ?
if [ -x /usr/bin/lame -a ! -e $install_dir/transcode/lame ]; then   # Check if 'lame' is installed, executable and that the symlink doesn't exist
	ln -s /usr/bin/lame $install_dir/transcode
fi

# Ensure links belong to the $app user
chown $app $install_dir/transcode

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating configuration..."

#ynh_config_add --template="systemd-sysconfig" --destination="/etc/default/$app"
#chmod 600 "/etc/default/$app"
#chown $app:$app "/etc/default/$app"

#ynh_config_add --template="airsonic.properties" --destination="$install_dir/airsonic.properties"
#chmod 600 "$install_dir/airsonic.properties"
#chown $app:$app "$install_dir/airsonic.properties"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# USE MULTIMEDIA
#=================================================
ynh_script_progression "Using multimedia..."

# Use multimedia folder if needed
if ! grep -q "/home/yunohost.multimedia/share/Music" $install_dir/db/airsonic.script; then
	ynh_systemctl --service=$app --action="stop"

	# Use multimedia folder
	ynh_replace --match="INSERT INTO MUSIC_FOLDER VALUES(0,'/var/music','Music'" --replace="INSERT INTO MUSIC_FOLDER VALUES(0,'/home/yunohost.multimedia/share/Music','YunoHost Music'" --file="$install_dir/db/airsonic.script"

	ynh_script_progression "Restarting a systemd service..."

	# Start a systemd service
	ynh_systemctl --service=$app --action="start" --log_path="$install_dir/airsonic.log" --wait_until="Started Application in"
fi

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Upgrading logrotate configuration..."

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate "$install_dir/$app.log"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="Airsonic daemon" --log="$install_dir/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="$install_dir/airsonic.log" --wait_until="Started Application in"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
